Rewrite the save_part_by_*() functions as a command chain
From this point, we try to define the clone operation as a chain of 3 tools:
- the cloner,
- the compressor, and
- the splitter.

Each one have its own inner working, but they can always be piped as:
cmd_chain="$cmd_clone | $cmd_compress | $cmd_split"

This is a second step to unify the save_part_by_* functions and have a
better error handling in the end. The error handling will have to work with
PIPESTATUS, since $? only contains the result code from the last command
used in a pipe chain.

Signed-off-by: Patrick Rouleau <pfrouleau@gmail.com>

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -1088,13 +1088,13 @@ save_part_by_ntfsclone() {
     echo "WARNING!!! ntfsclone is run with extra option(s): $ntfsclone_save_extra_opt"
     [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   fi
-  build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).ntfs-img"
-  ( ntfsclone $ntfsclone_save_extra_opt_def $ntfsclone_save_extra_opt --save-image --output - $source_dev | \
-    $compress_prog_opt | \
-    $cmd_split \
-  ) 2>&1 | \
-  tee $ntfs_img_info_tmp
-  rc="$?"
+  cmd_clone="ntfsclone $ntfsclone_save_extra_opt_def $ntfsclone_save_extra_opt --save-image --output - $source_dev"
+  build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).ntfs-img" "$split_error"
+  cmd_chain="$cmd_clone | $compress_prog_opt | $cmd_split"
+  echo "Run partclone: $cmd_chain" | tee --append ${OCS_LOGFILE}
+  LC_ALL=C eval "(${cmd_chain} && exit \${PIPESTATUS[0]})"
+#  ( $cmd_clone | $compress_prog_opt | $cmd_split ) 2>&1 | tee $ntfs_img_info_tmp
+  rc="$?" # return code from tee
   end_time="$(date +%s%N)"
   # UGLY! Since we use ntfsclone, then pipe to compression program, then IO redirect to file, the error control is weak. ntfsclone wil not exit even if the disk is full. Therefore we check here.
   echo "Checking the disk space... " && disk_full_test $image_name_ "The saved image file $tgt_dir/${tgt_file}.ntfs-img is incomplete! You have to increase the disk space, then start clonezilla save mode again."
@@ -1208,10 +1208,11 @@ save_part_by_partclone() {
   split_error="$(mktemp /tmp/split_error.XXXXXX)"
   trap "[ -f "$split_error" ] && rm -f $split_error" HUP INT QUIT TERM EXIT
 
-  cmd_partclone="partclone.${fs_p} $PARTCLONE_SAVE_OPT -L $partclone_img_info_tmp -c -s $source_dev --output - | $compress_prog_opt"
+  cmd_clone="partclone.${fs_p} $PARTCLONE_SAVE_OPT -L $partclone_img_info_tmp -c -s $source_dev --output -"
   build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).${fs_pre}-img.${comp_suf}" "$split_error"
-  echo "Run partclone: $cmd_partclone | $cmd_split" | tee --append ${OCS_LOGFILE}
-  LC_ALL=C eval "(${cmd_partclone | $cmd_split} && exit \${PIPESTATUS[0]})"
+  cmd_chain="$cmd_clone | $compress_prog_opt | $cmd_split"
+  echo "Run partclone: $cmd_chain" | tee --append ${OCS_LOGFILE}
+  LC_ALL=C eval "(${cmd_chain} && exit \${PIPESTATUS[0]})"
   rc="$?"
   cat "${partclone_img_info_tmp}" >> ${OCS_LOGFILE}
   end_time="$(date +%s%N)"
@@ -1270,10 +1271,11 @@ save_part_by_partimage() {
   # it is important to run partimage in save mode with volume=0 and -B gui=no
   # so that we can send the data to stdout
   start_time="$(date +%s%N)"
-  cmd_partimage="partimage $DEFAULT_PARTIMAGE_SAVE_OPT $PARTIMAGE_SAVE_OPT -B gui=no save $source_dev stdout | $compress_prog_opt"
-  build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file})"
-  echo "Run partimage: $cmd_partimage | $cmd_split" | tee --append ${OCS_LOGFILE}
-  LC_ALL=C eval "(${cmd_partimage | $cmd_split} && exit \${PIPESTATUS[0]})"
+  cmd_clone="partimage $DEFAULT_PARTIMAGE_SAVE_OPT $PARTIMAGE_SAVE_OPT -B gui=no save $source_dev stdout"
+  build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file})" "$split_error"
+  cmd_chain="$cmd_clone | $compress_prog_opt | $cmd_split"
+  echo "Run partimage: $cmd_chain" | tee --append ${OCS_LOGFILE}
+  LC_ALL=C eval "(${cmd_chain} && exit \${PIPESTATUS[0]})"
   rc="$?"
   end_time="$(date +%s%N)"
   calculate_elapsed_time $start_time $end_time
@@ -1345,25 +1347,16 @@ save_part_by_dd() {
     trigger_dd_status_report $source_dev $part_size &
     dd_report_sig_pid=$!
     start_time="$(date +%s%N)"
-    dd_retcode_file="$(mktemp /tmp/dd_retcode.XXXXXX)"
-    echo 1 > $dd_retcode_file
-    build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).dd-img"
-    #
-    ( 
-      (
-        LC_ALL=C dd bs=1M if=$source_dev $dd_save_extra_opt
-        echo $? > $dd_retcode_file
-      ) \
-      | $compress_prog_opt \
-      | $cmd_split
-    ) 2>&1 \
-    | tee $dd_img_info_tmp
-    tail -n 30 "${dd_img_info_tmp}" >> ${OCS_LOGFILE}
-    dd_retcode="$(cat $dd_retcode_file)"
+    cmd_clone="LC_ALL=C dd bs=1M if=$source_dev $dd_save_extra_opt 2> $dd_img_info_tmp"
+    build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).dd-img" "$split_error"
+    cmd_chain="$cmd_clone | $compress_prog_opt | $cmd_split | tee $dd_img_info_tmp 2>&1"
+    echo "Run partclone: $cmd_chain" | tee --append ${OCS_LOGFILE}
+    LC_ALL=C eval "(${cmd_chain} && exit \${PIPESTATUS[0]})"
+    dd_retcode="$?"
+    tail -n 30 "${dd_img_info_tmp}" | tee -a ${OCS_LOGFILE}
     if [ "$dd_retcode" = "0" ]; then
       echo "dd successfully cloned the device ($source_dev) to the image (-)" | tee --append ${OCS_LOGFILE}
     fi
-    rm -f $dd_retcode_file
     rc=$dd_retcode
 
     end_time="$(date +%s%N)"
@@ -1393,10 +1386,11 @@ save_part_by_dd() {
     split_error="$(mktemp /tmp/split_error.XXXXXX)"
     trap "[ -f "$split_error" ] && rm -f $split_error" HUP INT QUIT TERM EXIT
 
-    cmd_partclone="partclone.dd $PARTCLONE_SAVE_OPT -L $partclone_img_info_tmp -s $source_dev --output - | $compress_prog_opt"
+    cmd_clone="partclone.dd $PARTCLONE_SAVE_OPT -L $partclone_img_info_tmp -s $source_dev --output -"
     build_cmd_split "$VOL_LIMIT" "$tgt_dir/$(to_filename ${tgt_file}).dd-img" "$split_error"
-    echo "Run partclone: $cmd_partclone | $cmd_split" | tee --append ${OCS_LOGFILE}
-    LC_ALL=C eval "(${cmd_partclone | $cmd_split} && exit \${PIPESTATUS[0]})"
+    cmd_chain="$cmd_clone | $compress_prog_opt | $cmd_split"
+    echo "Run partclone: $cmd_chain" | tee --append ${OCS_LOGFILE}
+    LC_ALL=C eval "(${cmd_chain} && exit \${PIPESTATUS[0]})"
     rc="$?"
     cat "${partclone_img_info_tmp}" >> ${OCS_LOGFILE}
     end_time="$(date +%s%N)"
